### ISSUE TITLE
Cannot push a branch for addition our organization as DeAI Manifesto signee

### ISSUE THREAD

**Issue by TDarkDev** [DeAIWorkingGroupInternetComputer/ManifestoForDecentralizedAI#8]
FormyFi wants to be added to the list of DeAI Manifesto signee Organization, but having some issues while trying to push local branch for PR.

![image](https://github.com/user-attachments/assets/52853a14-371c-4a05-94a9-c1b092113b9b)
Can some enable open contribution?

**Comment by patnorris** [comment]
Hi there and thank you for contributing. Please fork the repo and create a PR from your forked repo.

This is a successful PR as an example: https://github.com/DeAIWorkingGroupInternetComputer/ManifestoForDecentralizedAI/pull/1

**Comment by TDarkDev** [comment]
> Hi there and thank you for contributing. Please fork the repo and create a PR from your forked repo.
> 
> This is a successful PR as an example: #1

Done, Thank you!
Here is the [PR](https://github.com/DeAIWorkingGroupInternetComputer/ManifestoForDecentralizedAI/pull/9).
